image: golang:latest

variables:
  GIT_SSL_CAPATH: /etc/ssl/certs/
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir -pv $CI_PROJECT_DIR /go/src/git.maglab.space/$CI_PROJECT_PATH
  - cp -vRT $CI_PROJECT_DIR /go/src/git.maglab.space/$CI_PROJECT_PATH
  - cd /go/src/git.maglab.space/$CI_PROJECT_PATH

stages:
    - test
    - build

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/snmp2mqtt
    artifacts:
      paths:
        - heatctld
